# Numpy Exercises

For this assigment you will need to have numpy installed. 

You can do this by typing 

``pip install -r requirements.txt``

with the `requirements.txt` file in the lecture material, or simply by

``pip install numpy``

## Important:
For this assignment, you may NOT use any loops! Think instead of how to use numpy functionality. Remember, loops are slow, numpy is faster, and efficiency matters.

## Also important (you will get points subtracted if you won't follow these rules):
 - **Only edit existing cells**
 - **DO NOT ADD NEW CELLS**
 - **DO NOT DELETE CELLS**
 - - **DO NOT ADD NEW CELLS**
Please do NOT add any new cells. Please ONLY type your new code where it says ``Your code here` and otherwise do NOT change anything else. This ensures that autograding will work properly.

# Assignment 4.1: Creating 1D Arrays

Write a function ``assignment_04_01`` that uses ``np.arange`` to create a one dimensional ``numpy`` array with the numbers [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30].


In [31]:
import numpy as np

def assignment_04_01():
    result = np.arange(0,31,3)
    return result

assignment_04_01()

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [32]:
# Test for your implementation
# if this does not raise an error, your code should work

correct = np.array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])
your_solution = assignment_04_01()
assert np.array_equal(your_solution, correct)

# Assignment 4.2: Creating 2D Arrays

Write a function ``assignment_04_02`` that creates a ``numpy`` array with 4 rows and 5 columns. The content of the array should be 1 for all cells initially as here:

```
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
```

Then, the function should *multiply each column by its column index plus 1* and then *subtract its respective row index* resulting in this matrix/array

```
array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.],
       [-2., -1.,  0.,  1.,  2.]])
```

In [33]:
import numpy as np

def assignment_04_02():
    
    result = np.ones((4, 5)) # Erstellen eines 4x5-Arrays mit 1en
    
    
    
    col_indices = np.arange(1, result.shape[1] + 1)  # Multiplizieren jeder Spalte mit ihrem Index plus 1
    result *= col_indices
    
    
    row_indices = np.arange(result.shape[0]).reshape(-1, 1)  # Subtrahieren des Zeilenindex von jeder Zeile
    result -= row_indices
    
    return result


assignment_04_02()

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.],
       [-2., -1.,  0.,  1.,  2.]])

In [34]:
correct = np.array([[ 1.,  2.,  3.,  4.,  5.],
                        [ 0.,  1.,  2.,  3.,  4.],
                        [-1.,  0.,  1.,  2.,  3.],
                        [-2., -1.,  0.,  1.,  2.]])
your_solution = assignment_04_02()
assert np.array_equal(your_solution, correct)

# Assignment 4.3: Indexing 2D Arrays

Write a function ``assignment_04_03`` that expects a ``numpy`` array with 4 rows and 5 columns. Then, extract the bold-faced subarray (the little circles below) and return it.

|   |   |   |   |   |
|:--|:-:|:-:|:-:|:--|
| . | . | . | . | . |
| . | **o** | **o** | **o** | . |
| . | **o** | **o** | **o** | . |
| . | . | . | . | . |



In [35]:
import numpy as np

def assignment_04_03(arr):
   
    subarray = arr[1:3, 1:4]
    return subarray


arr = np.ones((4, 5))
assignment_04_03(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
def assignment_04_03_test():
    arr = np.array([[ 1.,  2.,  3.,  4.,  5.],
                    [ 0.,  1.,  2.,  3.,  4.],
                    [-1.,  0.,  1.,  2.,  3.],
                    [-2., -1.,  0.,  1.,  2.]])
    correct = np.array([[1., 2., 3.],
                        [0., 1., 2.]])
    your_solution = assignment_04_03(arr)
    assert np.array_equal(your_solution, correct)
    
assignment_04_03_test()

# Assignment 4.4: Manipulating 2D Arrays

Write a function ``assignment_04_04`` that creates a ``numpy`` array with 100000 rows and 2 columns. The first column should contain normally distributed variables with mean 1 and standard deviation 2 and the second column should contain normally distributed variables with mean -2 and standard deviation 0.5. 



In [37]:
import numpy as np

def assignment_04_04():
      
    spalte1 = np.random.normal(1, 2,100000)    # loc=1 is mean, scale=2 is the standard deviation, size=100000 number of samples

    
   
    spalte2 = np.random.normal(-2,0.5,100000)

    
    result = np.column_stack((spalte1, spalte2)) # Combine the two columns into a single 2D array
    
    return result


In [38]:
result = assignment_04_04()
true_mean = np.array([1,-2])
true_std = np.array([2., 0.5])
mean_diff = result.mean(axis=0) - true_mean
std_diff = result.std(axis=0) - true_std
assert all(np.hstack([mean_diff, std_diff]) < 0.1)